# Generated by Django 5.2.17 on 2026-08-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=20)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RECOVERED', 'Recovered'), ('PENDING', 'Pending'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('ai_diagnosis', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('recovery_action', models.CharField(blank=True, max_length=255)),
                ('recovery_result', models.CharField(blank=True, max_length=255)),
                ('revenue_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
