# Generated by Django 5.2.17 on 2026-08-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ai_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recovery_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recovery_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RecoveryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(blank=True, max_length=100, null=True)),
                ('root_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_action', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_action', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed', models.BooleanField(default=False)),
                ('executed', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_audits', to='payments.payment')),
            ],
        ),
    ]
