# Generated by Django 5.2.17 on 2026-08-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryaudit',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
