# Generated by Django 5.2.17 on 2026-08-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_user_alter_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ai_diagnosis',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recovery_action',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recovery_result',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='FAILED', max_length=50),
        ),
    ]
